version: '3'
services:
  app:
    image: jp/app:latest
    container_name: app
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
  nginx:
    image: nginx:1.26.1-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  mysql:
    image: mysql:8.4.2
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jp123
      MYSQL_DATABASE: challenge
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5